name: gallery
description: Gallery project to showcase {{project_name.snakeCase()}}_ui
version: 0.0.1
publish_to: none

environment:
  sdk: "{{{sdk_version}}}"

dependencies:
  {{project_name.snakeCase()}}_ui:
    path: ../
  flutter:
    sdk: flutter
  flutter_asset_generator: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
