name: internationalization
description: All the translations for Converter NOW.

publish_to: "none"

resolution: workspace

version: 1.0.0

environment:
  sdk: "{{{sdk_version}}}"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
