name: {{project_name.snakeCase()}}_ui
description: {{project_name.pascalCase()}} UI library
version: 0.1.0
publish_to: none

resolution: workspace

environment: 
  sdk: "{{{sdk_version}}}"

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_asset_generator: ^1.1.0
  flutter_svg: ^2.0.10+1
  vector_graphics: ^1.1.11+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.4
  flutter_gen_runner: ^5.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: NotoSansDisplay
      fonts:
        - asset: assets/fonts/NotoSansDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansDisplay-SemiBold.ttf
          weight: 600
  

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true
      
  line_length: 80

  integrations:
    flutter_svg: true