include: package:xsoulspace_lints/app.yaml

analyzer:
  exclude:
    - bin/cache/*
    # json_serializable
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    # Please do not change this to lib wide
    # rule, since the app_router.gr.dart can often
    # be cause of missing dependencies.
    - lib/ui/components/**.*.dart
    - lib/ui/pages/**.*.dart
    - lib/l10n/l10n.dart
    - lib/l10n/l10n_*.dart

  errors:
    invalid_annotation_target: ignore
    unused_local_variable: info
    require_trailing_commas: error
    flutter_style_todos: error
  # plugins:
  #   - dart_code_metrics
linter:
  rules:
    avoid_annotating_with_dynamic: false

dart_code_metrics:

  metrics:
    cyclomatic-complexity: 20
    lines-of-executable-code: 50
    number-of-parameters: 5
    maximum-nesting-level: 5

  metrics-exclude:
    exclude:
      - bin/cache/*
      - ./**.*.dart
      - lib/l10n/l10n.dart
      - lib/l10n/l10n_*.dart

  rules:
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
