name: core
description: The Core package of {{name.pascalCase()}}.
version: 0.1.0
publish_to: none

resolution: workspace

environment:
  sdk: "{{{sdk_version}}}"

dependencies:
  built_collection: ^5.1.1
  device_info_plus: ^11.2.0   
  dio: ^5.7.0
  {{#graphql}}
  ferry: ^0.14.2+1
  # ferry_hive_store: ^0.5.1
  {{/graphql}}
  firebase_analytics: ^11.3.6
  firebase_core: ^3.9.0
  firebase_crashlytics: ^4.2.0
  firebase_messaging: ^15.1.6
  firebase_performance: ^0.10.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.3
  formz: ^0.8.0
  freezed_annotation: ^2.4.4
  {{#graphql}}
  gql_exec: ^1.0.0
  gql_http_link: ^1.0.1
  {{/graphql}}
  http_parser: ^4.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  internationalization: ^1.0.0
  package_info_plus: ^8.1.2
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  provider: ^6.1.2
  retrofit: ^4.4.2
  rxdart: ^0.28.0
  shared_preferences: ^2.3.5
  uuid: ^4.5.1
  version: ^3.0.2

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  json_serializable: ^6.7.1
  retrofit_generator: ^9.1.7
  very_good_analysis: ^7.0.0
  xsoulspace_lints: ^0.0.11