#!/usr/bin/env bash

script_file="$(readlink -f -- $0)"
hooks_dir="$(dirname -- $script_file)"
scripts_dir="$(dirname -- $hooks_dir)"
project_dir="$(dirname -- $scripts_dir)"

# Format flutter code
# $scripts_dir/format.sh

# if [ $? -ne 0 ]; then
#     echo "formatter rewrote files, please add this changes before committing"
#     exit 1
# fi

