name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 1.0.0+1
publish_to: none

environment:
  sdk: "{{{sdk_version}}}"

workspace:
  - packages/{{project_name.snakeCase()}}_ui
  - packages/core
  - packages/internationalization

dependencies:
  {{project_name}}_ui: 0.1.0
  bloc: ^8.1.3
  core: 0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  internationalization: 1.0.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0
  mocktail: ^1.0.3
  freezed: ^2.5.7
  json_serializable: ^6.7.1
  very_good_analysis: ^7.0.0
  xsoulspace_lints: ^0.0.10


flutter:
  uses-material-design: true
  generate: true
